version: 2

jobs:
  test:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt update
      - run:
          name: Install dependencies
          command: apt install -y git make cmake clang-format g++ libncurses5-dev libncursesw5-dev
      - run:
          name: Check formating
          command: |
            make format
            git diff --exit-code
      - run:
          name: Build
          command: make build

workflows:
  version: 2
  test:
      jobs:
        - test
